image:
  repository: cm2network/squad
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  game1port: 7787
  game2port: 7788
  query1port: 27165
  query2port: 27166
  rconport: 21114

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
