image:
  repository: cm2network/squad
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  gamePort: 7787
  queryPort: 27165
  rconPort: 21114

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
