apiVersion: v1
kind: Service
metadata:
  name: {{ include "squad.fullname" . }}
  labels:
    {{- include "squad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.gamePort }}
      targetPort: game-udp
      protocol: UDP
      name: game-udp
    - port: {{ .Values.service.queryPort }}
      targetPort: query-udp
      protocol: UDP
      name: query-udp
    - port: {{ .Values.service.queryPort }}
      targetPort: query-tcp
      protocol: TCP
      name: query-tcp
  selector:
    {{- include "squad.selectorLabels" . | nindent 4 }}
